Add support for inherits and class references
voxpupuli/puppet-lint-absolute_classname-check pull request #23
Opened 2020-10-17 14:23 UTC by bodgit

Now detects violations such as:
```puppet
class foo inherits ::bar {}
```
and
```puppet
Class['::foo'] -> Class['::bar']
```
Fixes #20

2020-10-17 16:19 UTC, alexjfisher commented
Good stuff.  I'd actually written an implementation a few days back, but hadn't gotten around to committing it yet!  I prefer yours though. :)

2020-10-17 16:21 UTC, alexjfisher commented on lib/puppet-lint/plugins/check_absolute_classname.rb
> +              message: message,
We should probably use a different message here?
`class included by absolute name` isn't accurate.

2020-10-17 16:24 UTC, alexjfisher requested changes
Looking good I think.  Could you update the README?

2020-10-17 16:42 UTC, alexjfisher commented
I can't decide whether the next release should be 3.0.0 or not.  I suppose this is 'breaking' in so much that lots of manifests that passed before, won't now.  'inherits' could be argued to be a way of including a class, but Class references aren't and checking them doesn't fall under the current gem's description (`A puppet-lint plugin to check that classes are included by their absolute name.`), which needs updating anyway.

@bodgit Could you update the gemspec with a new summary and description as well as updating the README?

2020-10-17 18:04 UTC, ekohl commented
I think this will work, but it's also valid to write `require => Class['::foo', '::bar']` and it should detect both. Another example would be `require => [Class['::foo'], Class['::bar']]`. Could you include tests for that as well?

2020-10-17 19:53 UTC, bodgit commented
> I think this will work, but it's also valid to write `require => Class['::foo', '::bar']` and it should detect both. Another example would be `require => [Class['::foo'], Class['::bar']]`. Could you include tests for that as well?

I'd forgotten about the first syntax, thankfully the code still works with some extra tests added.

2020-10-18 12:31 UTC, ekohl commented
Thanks for adding those tests. If you address https://github.com/voxpupuli/puppet-lint-absolute_classname-check/pull/23#discussion_r506958924 I think this should be good to merge.

2020-10-18 13:15 UTC, alexjfisher commented
I guess bare words and interpolated strings are also valid puppet?  Ideally the plugin would also detect (and fix)

```puppet
Class[::foo] -> Class["::foo::install::${osfamily}"]
```

Not a blocker for me though.

2020-10-18 15:00 UTC, bodgit commented
Is it worth making the class references check separate within this gem?

2020-10-18 16:50 UTC, alexjfisher commented
> Is it worth making the class references check separate within this gem?

Possibly.  That would let users turn it off if they didn't like it.  Or we could default it to off for a release and then turn it on in the next major release.

2020-10-18 16:59 UTC, alexjfisher commented
But like I said in https://github.com/voxpupuli/puppet-lint-absolute_classname-check/pull/23#issuecomment-711166515, getting it perfect is not a blocker.  I think the new check is already going to be covering 90%+ of uses.

For the existing checking of how classes are included, I can keep coming up with obscure corner cases too, but life isn't long enough to try and catch them all.

eg (I've seen this style in the last week, complete with random trailing comma and all those single quotes)

```puppet
include '::foo::bar', '::foo:foobar', 'foo',
```

or as an actual array (instead of the comma separated string above)
```puppet
include [::foo::bar,'foo','::foo::foobar']
```

I think even the following is valid and would compile just fine...
```puppet
[
  '::foo::bar',
  'foo',
  ::foo::foobar,
].include
```

2020-10-18 23:10 UTC, bodgit commented
I've split out the class reference check, updated the gemspec and README, and added support for bare class names as that was an easy addition. Anything else?

2020-10-20 18:20 UTC, alexjfisher approved these changes
@bodgit Superb contribution.  Thank you!

2020-10-20 18:21 UTC, merged